
# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
PANDABI_API_KEY ="PAI-8b03ecca-b787-4226-baba-64b1c9f068a8"