
# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
PANDABI_API_KEY ="PAI-8b03ecca-b787-4226-baba-64b1c9f068a8"